### ISSUE TITLE
Any thoughts on supporting Gentoo?

### ISSUE THREAD

**Issue by Phate6660** [keylo99/pkgtop#1]
As the title says, any chance on supporting Gentoo (portage)?

I've never worked with Go before, so I don't know how much I can help on that front. However I'm currently using Gentoo and I can help you with any commands you might need. (I saw that you call the package managers in the code for various information, which is why I brought it up.)

**Comment by keylo99** [comment]
Yes, I want pkgtop to support gentoo if it's possible. I have to test most of the distributions on my virtual machine so it hasn't come up to gentoo yet. But I'd be appreciated if you want to help with it.
I'll try to explain the command that I need with an example distribution:

```
pacman -Qi | awk '/^Name/{name=$3} /^Version/{ver=$3} /^Description/{desc=substr($0,index($0,$3))} /^Installed Size/{size=$4$5; print name ";" ver ";" size ";" desc}' | sort -h -r -t ';' -k3 && echo "pacman -Qi %s | sed -e 's/^/  /';pacman -Rcns %s --noconfirm;pacman -S %s --noconfirm;pacman -Sy %s --noconfirm;x"&& echo 'Name|Version|Installed Size|Description'
```

First part of the command prints the installed packages by size with the delimiter char '`;`' as follows.
```
pacman -Qi | awk '/^Name/{name=$3} /^Version/{ver=$3} /^Description/{desc=substr($0,index($0,$3))} /^Installed Size/{size=$4$5; print name ";" ver ";" size ";" desc}' | sort -h -r -t ';' -k3 
```
Output:
```
...
ca-certificates-utils;20181109-1;8.00KiB;Common CA certificates (utilities)
java-runtime-common;3-1;7.00KiB;Common files for Java Runtime Environments
...
```
The second part is printing the required commands to manage packages and the list titles.
```
echo "pacman -Qi %s | sed -e 's/^/  /';pacman -Rcns %s --noconfirm;pacman -S %s --noconfirm;pacman -Sy %s --noconfirm;x"&& echo 'Name|Version|Installed Size|Description'
```
Output:
```
pacman -Qi %s | sed -e 's/^/  /';pacman -Rcns %s --noconfirm;pacman -S %s --noconfirm;pacman -Sy %s --noconfirm;x
Name|Version|Installed Size|Description
```
So the command that I need is basically will print these information:
```
...
[name];[version];[size];[description]
...
[package information command] %s | sed -e 's/^/  /';[package remove command with no confirmation] %s ;[package install command with no confirmation] %s ;[package upgrade command with no confirmation] %s ;x
Name|Version|Installed Size|Description
```
I know it's a little bit complicated but I hope this would be helpful.

**Comment by Hess2906** [comment]
If I were to create the same commands but with ports and/or pkg on FreeBSD would you implement it?

**Comment by keylo99** [comment]
Yes, of course I can. That would be good actually.

**Comment by keylo99** [comment]
It looks like gentoo has multiple tools for listing packages and their information. (eix, equery, qsize) In this situation, it's even harder to parse packages with their description and size.

**Comment by keylo99** [comment]
But here's what I came up with:
```
qsize | sed 's/ non-files, /;/g; s/ files, /;/g; s/: /;/g' | sort -h -r -t ';' -k4
```
It does not contain description which is necessary. I'll keep searching until I found a command that is suitable for the pkgtop.

**Comment by keylo99** [comment]
#18
