### ISSUE TITLE
Might need to add a go.mod file to the src directory

### ISSUE THREAD

**Issue by ZahFox** [keylo99/pkgtop#11]
I tried installing pkgtop using the AUR method, but it failed with the following error message: 

> go: cannot determine module path for source directory ... (outside GOPATH, no import comments)

I noticed there wasn't any go.mod file for this project so I added one and after that I was able to install without any issues.

```go
module github.com/keylo99/pkgtop

go 1.12

require (
  github.com/atotto/clipboard v0.1.2
  github.com/dustin/go-humanize v1.0.0
  github.com/gizak/termui/v3 v3.1.0
)
```

**Comment by keylo99** [comment]
It's handled with the 6dad207. Thanks for creating the file & reporting this.
