### ISSUE TITLE
Don't work on arch

### ISSUE THREAD

**Issue by Feresey** [keylo99/pkgtop#12]
When I try to do something, it crashes.

For example, press '?' twice. No help, no navigation, no search, no installation.

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gizak/termui/v3/widgets.(*List).Draw(0xc00011e5a0, 0xc000084360)
	/home/lol/go/pkg/mod/github.com/gizak/termui/v3@v3.1.0/widgets/list.go:47 +0x8f4
github.com/gizak/termui/v3.(*Grid).Draw(0xc00011c1a0, 0xc000084360)
	/home/lol/go/pkg/mod/github.com/gizak/termui/v3@v3.1.0/grid.go:157 +0x1bb
github.com/gizak/termui/v3.Render(0xc0000552a0, 0x2, 0x2)
	/home/lol/go/pkg/mod/github.com/gizak/termui/v3@v3.1.0/render.go:25 +0x2a2
main.start(0x555d6e, 0xc, 0x0)
	pkgtop.go:560 +0x377c
main.main()
	pkgtop.go:648 +0x2bb
```

Arch linux, including testing repo. Go version: go1.12.9 linux/amd64

**Comment by Feresey** [comment]
Program screen (if you need)
![image](https://user-images.githubusercontent.com/33696249/64069778-a68e2580-cc59-11e9-9857-a58646335497.png)

**Comment by Feresey** [comment]
ahahah, i found a problem
LC_ALL=C pkgtop

**Comment by Feresey** [comment]
This is not an issue, but rather a bug that is important to fix.

**Comment by keylo99** [comment]
I'm going to check this locale issue. And no, it's not racism. (-,-)

**Comment by poldi1405** [comment]
Can confirm for german locale as well
