### ISSUE TITLE
Partial upgrades are unsupported in Arch

### ISSUE THREAD

**Issue by BrianAllred** [keylo99/pkgtop#16]
https://github.com/keylo99/pkgtop/blob/7710b5e85bafe4cc4fce65781fe5e2630a55881b/src/pkgtop.go#L56

`pacman -Sy` is specifically unsupported in Arch and could lead to dependency issues, according to [the Arch wiki](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported).

**Comment by keylo99** [comment]
I will change that command to `pacman -Syu` for fixing the problem. Thanks for reporting this.
