### ISSUE TITLE
Unable to locate package pkgtop

### ISSUE THREAD

**Issue by ricardoboss** [keylo99/pkgtop#3]
Hi there, came from your [Reddit post](https://www.reddit.com/r/linux/comments/cxn8oi/pkgtop_interactive_package_manager_resource/)!

I wanted to install it using apt and Ubuntu in WSL (Windows Subsystem for Linux):

```sh
sudo apt update
sudo apt install pkgtop
```

but got:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pkgtop
```

Any ideas?

**Comment by keylo99** [comment]
Hey,
There is no Ubuntu package available for installing the pkgtop yet.
So in this situation, you have to install it manually as shown [here](https://github.com/keylo99/pkgtop#-manual-insallation).
