### ISSUE TITLE
No borders

### ISSUE THREAD

**Issue by DuBistKomisch** [keylo99/pkgtop#4]
![image](https://user-images.githubusercontent.com/703055/64056232-13131100-cbd5-11e9-8e6a-24157190b558.png)

using 1.3 from AUR, using st as my terminal and hack as my font, maybe needs some more basic characters or a fallback option?

**Comment by DuBistKomisch** [comment]
oh, I'm dumb, the colour is just basically invisible for some reason

**Comment by shscs911** [comment]
Awesome work, man. This is a far better UI alternative than `pamac` or `octopi` in my Manjaro. My only gripe is the border visibiIity. Mine has borders, but they are really faint.
![Screenshot_20190831_143637](https://user-images.githubusercontent.com/44034402/64061775-c6dbc700-cbfc-11e9-89f0-c0543948c9e3.png)
Its not a deal breaker, but I'd love something like `gotop` borders. Keep up the good work.
![Screenshot_20190831_144042](https://user-images.githubusercontent.com/44034402/64061835-54b7b200-cbfd-11e9-8125-2d58ba43b7cf.png)

**Comment by keylo99** [comment]
Borders are set to color black and visibility depends on your terminal colors. I think it's looking good like this but I'll try to improve it. Thanks!
