### ISSUE TITLE
Out of bounds rendering crash

### ISSUE THREAD

**Issue by DSsoto** [keylo99/pkgtop#6]
Hi, first of all thanks for the tool! It seems like it can be very useful. 
I ran into this out of bounds bug, here are the steps to reproduce:
* run `pkgtop`
* press `s`
* enter query for package that gives multiple results (without pressing enter)
* press down arrow couple of times to look at another package
* press `?`

The program should crash with this stack trace:
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic
        ../../../src/libgo/go/runtime/panic.go:554
runtime_panicstring
        ../../../src/libgo/runtime/panic.c:38
github_com_gizak_termui_v3_widgets.List.Draw
        ${HOME}/go/src/github.com/gizak/termui/v3/widgets/list.go:47
github_com_gizak_termui_v3.Render
        ${HOME}/go/src/github.com/gizak/termui/v3/render.go:25
main.scrollLists
        ${HOME}/go/src/pkgtop/src/pkgtop.go:249
main.start
        ${HOME}/go/src/pkgtop/src/pkgtop.go:432
main.main
        ${HOME}/go/src/pkgtop/src/pkgtop.go:648

```

**Comment by keylo99** [comment]
It's fixed with the 59334db.
Thanks for the report.
