### ISSUE TITLE
Voidlinux (xbps) support?

### ISSUE THREAD

**Issue by lugubris** [keylo99/pkgtop#7]
I'll be able to help with command outputs.

xbps-query -> https://wiki.voidlinux.org/XBPS#xbps-query

manual -> https://man.voidlinux.org/xbps-query.1

**Comment by keylo99** [comment]
That would be great. I've explained the commands that I use at #1 if you want to help. Otherwise I need time for implementing this.

**Comment by keylo99** [comment]
xbps-query command is not showing the package size. pkgtop should parse the package name-version-size-description, otherwise that would be unhandy.

**Comment by keylo99** [comment]
Anyway, here's what I came up with: #14 
@lugubris I can merge the pull request if you test it and send me a screenshot.

**Comment by keylo99** [comment]
#14
